name: Brian Knapp
favicon: null
layout_spectrum: 0.14336
typography_spectrum: 0.29698
title: Brian Knapp
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#030102'
    - '#34465a'
    - '#acc0c1'
    - '#858086'
  brandStrength: 0.125
  lightness: 0.7132989349775016
  saturation: 0.6247822009027004
  rhythmicContrast: 0.8194990779738873
purpose: []
